
alias py=python 
alias ipy=ipython
alias vact="source venv/bin/activate" 
alias g=git 
alias v=nvim 
alias vim=nvim
alias eza='eza --icons'
alias ls=eza
alias lsa="ls -a"
alias ll="ls -la"
alias lla="ll -a"
alias :q=exit
alias runserver="py manage.py runserver"
alias ch="code ."
alias c=code 
alias ci=code-insiders
alias cleanpull='git reset --hard'
alias gacp='git add . ; git commit; git push --force'
alias update_desktop_items="sudo ln -s ~/.local/share/applications/* /usr/share/applications/"
alias fetch='neofetch' 
alias cls=clear
alias srunserver='sudo python manage.py runserver'
alias runserver='python manage.py runserver'
alias flushredis="redis-cli flushall; clear; echo Cache Cleared"
